### ISSUE TITLE
serveStatic doesn't work as expected

### ISSUE THREAD

**Issue by burakkilic** [restify/plugins#13] opened 2016-02-10 23:16 UTC
Hi;

I am trying to serve 2 apps with serveStatic plugin.

server.get('/app1', restify.serveStatic({
    directory: __dirname + '/shared/.build',
    default: 'index.html'
}));

is not working but

server.use('/app1', express.static(__dirname + '/shared/.build'));

works as expected. 

Where am I wrong?

**Comment by retrohacker** [comment] 2017-05-09 23:52
Hey @burakkilic,

I believe this is a duplicate of https://github.com/restify/node-restify/issues/1076

We are migrating plugins back into the main repo. If I've missed a nuance here, please re-open an issue at https://github.com/restify/node-restify/issues and I can help add context :smile:

**Closed as completed by retrohacker** 2017-05-09 23:52 UTC
