### ISSUE TITLE
Make test error

### ISSUE THREAD

**Issue by andrevandal** [restify/plugins#30] opened 2016-05-15 08:51 UTC
Hi, I'm wanna contribute with bearer authorization parse but when I use "make test", returns some [errors](http://pastebin.com/raSBjp4H)...
Could you iluminate me? :)

**Comment by DonutEspresso** [comment] 2016-05-16 02:35
I was able to repro using Node6. Looks like breaking change was made to the core API, the tests will need to be updated. In the meantime, try Node4 and see if that works for you?

**Comment by DonutEspresso** [comment] 2016-07-07 23:39
Fixed by #38. Also a dupe of #37

**Closed as completed by DonutEspresso** 2016-07-07 23:39 UTC
